### ISSUE TITLE
Error during npm run dev

### ISSUE THREAD

**Issue by lesaff** [andrefelipe/vite-php-setup#3]
I am getting this error when I ran `npm run dev` 

Is there a specific minimum npm version required?

```
npm run dev
(node:90716) ExperimentalWarning: The fs.promises API is experimental

> my-php-project@0.0.0 dev
> APP_ENV=development vite

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Volumes/SanDisk1TB/Sites/vite-php-setup/vite/node_modules/vite/dist/node/chunks/dep-d13406fa.js:18:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code 1
npm ERR! path /Volumes/#####/Sites/vite-php-setup/vite
npm ERR! command failed
npm ERR! command sh -c APP_ENV=development vite
```

**Comment by andrefelipe** [comment]
I'm not sure. But should be npm or node version. 

I am on Node v15.10.0 and NPM 7.5.3

**Comment by lesaff** [comment]
```
npm -v
(node:92713) ExperimentalWarning: The fs.promises API is experimental
7.5.2

node -v
v10.16.3
```

UPDATE: I've updated both npm and node to match yours and it is working. I think you should amend the readme to add minimum requirement of `node: '>=12.0.0'`

Cheers
